# -*- coding: utf-8 -*-
"""4110E004_1004.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1r5tAQRZ0whTZPm4RNk7RI6fsDu1VmOuy
"""

#python
a = """Lorem ipsum dolor sit amet,
consectetur adipiscing elit,
sed do eiusmod tempor incididunt
ut labore et dolore magna aliqua."""
print(a)

#python
a = "Hello, World!"
print(a[1])

#python
txt = "The best things in life are free!"
if "free" in txt:
  print("Yes, 'free' is present.")

#python
txt = "The best things in life are free!"
if "expensive" not in txt:
  print("No, 'expensive' is NOT present.")

#python
b = "Hello, World!"
print(b[2:5])

#python
b = "Hello, World!"
print(b[:5])

#python
b = "Hello, World!"
print(b[-5:-2])

#python
a = " Hello, World! "
print(a.strip())

#python
thislist = ["apple", "banana", "cherry"]
print(thislist)

#python
list1 = ["apple", "banana", "cherry"]
list2 = [1, 5, 7, 9, 3]
list3 = [True, False, False]

print(list1)
print(list2)
print(list3)

#python
thislist = ["apple", "banana", "cherry"]
print(thislist[1])

#python
thislist = ["apple", "banana", "cherry"]
print(thislist[-1])

#python
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "melon", "mango"]
print(thislist[2:5])

#python
thislist = ["apple", "banana", "cherry"]
if "apple" in thislist:
  print("Yes, 'apple' is in the fruits list")

#python
thislist = ["apple", "banana", "cherry"]
thislist[1] = "blackcurrant"

print(thislist)

#python
thislist = ["apple", "banana", "cherry", "orange", "kiwi", "mango"]

thislist[1:3] = ["blackcurrant", "watermelon"]

print(thislist)

#python
thislist = ["apple", "banana", "cherry"]

thislist.insert(2, "watermelon")

print(thislist)

#python
thislist = ["apple", "banana", "cherry"]

thislist.append("orange")

print(thislist)

#python
thislist = ["apple", "banana", "cherry"]
tropical = ["mango", "pineapple", "papaya"]

thislist.extend(tropical)

print(thislist)

#python
a = "Hello, World!"
print(a.replace("H", "J"))